/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BarcodesRouteImport } from './routes/barcodes'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as PosRouteImport } from './routes/pos'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PurchaseReturnsRouteImport } from './routes/purchase-returns'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as SaleReturnsRouteImport } from './routes/sale-returns'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StockMovementsRouteImport } from './routes/stock-movements'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ZReportRouteImport } from './routes/z-report'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsAccountBalancesRouteImport } from './routes/reports.account-balances'
import { Route as ReportsBalanceSheetRouteImport } from './routes/reports.balance-sheet'
import { Route as ReportsCashbookRouteImport } from './routes/reports.cashbook'
import { Route as ReportsExpensesRouteImport } from './routes/reports.expenses'
import { Route as ReportsExpiryRouteImport } from './routes/reports.expiry'
import { Route as ReportsInventoryValuationRouteImport } from './routes/reports.inventory-valuation'
import { Route as ReportsLowStockRouteImport } from './routes/reports.low-stock'
import { Route as ReportsPayablesRouteImport } from './routes/reports.payables'
import { Route as ReportsProfitLossRouteImport } from './routes/reports.profit-loss'
import { Route as ReportsPurchasesRouteImport } from './routes/reports.purchases'
import { Route as ReportsReceivablesRouteImport } from './routes/reports.receivables'
import { Route as ReportsSalesRouteImport } from './routes/reports.sales'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as CustomersIdLedgerRouteImport } from './routes/customers.$id.ledger'
import { Route as PrintPurchaseIdRouteImport } from './routes/print.purchase.$id'
import { Route as PrintReceiptIdRouteImport } from './routes/print.receipt.$id'
import { Route as SuppliersIdLedgerRouteImport } from './routes/suppliers.$id.ledger'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BarcodesRoute = BarcodesRouteImport.update({
  id: '/barcodes',
  path: '/barcodes',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseReturnsRoute = PurchaseReturnsRouteImport.update({
  id: '/purchase-returns',
  path: '/purchase-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleReturnsRoute = SaleReturnsRouteImport.update({
  id: '/sale-returns',
  path: '/sale-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StockMovementsRoute = StockMovementsRouteImport.update({
  id: '/stock-movements',
  path: '/stock-movements',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ZReportRoute = ZReportRouteImport.update({
  id: '/z-report',
  path: '/z-report',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAccountBalancesRoute = ReportsAccountBalancesRouteImport.update({
  id: '/reports/account-balances',
  path: '/reports/account-balances',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsBalanceSheetRoute = ReportsBalanceSheetRouteImport.update({
  id: '/reports/balance-sheet',
  path: '/reports/balance-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCashbookRoute = ReportsCashbookRouteImport.update({
  id: '/reports/cashbook',
  path: '/reports/cashbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsExpensesRoute = ReportsExpensesRouteImport.update({
  id: '/reports/expenses',
  path: '/reports/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsExpiryRoute = ReportsExpiryRouteImport.update({
  id: '/reports/expiry',
  path: '/reports/expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsInventoryValuationRoute =
  ReportsInventoryValuationRouteImport.update({
    id: '/reports/inventory-valuation',
    path: '/reports/inventory-valuation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsLowStockRoute = ReportsLowStockRouteImport.update({
  id: '/reports/low-stock',
  path: '/reports/low-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPayablesRoute = ReportsPayablesRouteImport.update({
  id: '/reports/payables',
  path: '/reports/payables',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsProfitLossRoute = ReportsProfitLossRouteImport.update({
  id: '/reports/profit-loss',
  path: '/reports/profit-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPurchasesRoute = ReportsPurchasesRouteImport.update({
  id: '/reports/purchases',
  path: '/reports/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReceivablesRoute = ReportsReceivablesRouteImport.update({
  id: '/reports/receivables',
  path: '/reports/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSalesRoute = ReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuppliersRoute,
} as any)
const CustomersIdLedgerRoute = CustomersIdLedgerRouteImport.update({
  id: '/$id/ledger',
  path: '/$id/ledger',
  getParentRoute: () => CustomersRoute,
} as any)
const PrintPurchaseIdRoute = PrintPurchaseIdRouteImport.update({
  id: '/print/purchase/$id',
  path: '/print/purchase/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintReceiptIdRoute = PrintReceiptIdRouteImport.update({
  id: '/print/receipt/$id',
  path: '/print/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdLedgerRoute = SuppliersIdLedgerRouteImport.update({
  id: '/$id/ledger',
  path: '/$id/ledger',
  getParentRoute: () => SuppliersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/barcodes': typeof BarcodesRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRouteWithChildren
  '/errors': typeof ErrorsRoute
  '/expenses': typeof ExpensesRoute
  '/incidents': typeof IncidentsRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/purchase-returns': typeof PurchaseReturnsRoute
  '/purchases': typeof PurchasesRoute
  '/sale-returns': typeof SaleReturnsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock-movements': typeof StockMovementsRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/users': typeof UsersRoute
  '/z-report': typeof ZReportRoute
  '/reports/account-balances': typeof ReportsAccountBalancesRoute
  '/reports/balance-sheet': typeof ReportsBalanceSheetRoute
  '/reports/cashbook': typeof ReportsCashbookRoute
  '/reports/expenses': typeof ReportsExpensesRoute
  '/reports/expiry': typeof ReportsExpiryRoute
  '/reports/inventory-valuation': typeof ReportsInventoryValuationRoute
  '/reports/low-stock': typeof ReportsLowStockRoute
  '/reports/payables': typeof ReportsPayablesRoute
  '/reports/profit-loss': typeof ReportsProfitLossRoute
  '/reports/purchases': typeof ReportsPurchasesRoute
  '/reports/receivables': typeof ReportsReceivablesRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/customers/': typeof CustomersIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/customers/$id/ledger': typeof CustomersIdLedgerRoute
  '/print/purchase/$id': typeof PrintPurchaseIdRoute
  '/print/receipt/$id': typeof PrintReceiptIdRoute
  '/suppliers/$id/ledger': typeof SuppliersIdLedgerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/barcodes': typeof BarcodesRoute
  '/categories': typeof CategoriesRoute
  '/errors': typeof ErrorsRoute
  '/expenses': typeof ExpensesRoute
  '/incidents': typeof IncidentsRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/purchase-returns': typeof PurchaseReturnsRoute
  '/purchases': typeof PurchasesRoute
  '/sale-returns': typeof SaleReturnsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock-movements': typeof StockMovementsRoute
  '/users': typeof UsersRoute
  '/z-report': typeof ZReportRoute
  '/reports/account-balances': typeof ReportsAccountBalancesRoute
  '/reports/balance-sheet': typeof ReportsBalanceSheetRoute
  '/reports/cashbook': typeof ReportsCashbookRoute
  '/reports/expenses': typeof ReportsExpensesRoute
  '/reports/expiry': typeof ReportsExpiryRoute
  '/reports/inventory-valuation': typeof ReportsInventoryValuationRoute
  '/reports/low-stock': typeof ReportsLowStockRoute
  '/reports/payables': typeof ReportsPayablesRoute
  '/reports/profit-loss': typeof ReportsProfitLossRoute
  '/reports/purchases': typeof ReportsPurchasesRoute
  '/reports/receivables': typeof ReportsReceivablesRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/customers': typeof CustomersIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/customers/$id/ledger': typeof CustomersIdLedgerRoute
  '/print/purchase/$id': typeof PrintPurchaseIdRoute
  '/print/receipt/$id': typeof PrintReceiptIdRoute
  '/suppliers/$id/ledger': typeof SuppliersIdLedgerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/barcodes': typeof BarcodesRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRouteWithChildren
  '/errors': typeof ErrorsRoute
  '/expenses': typeof ExpensesRoute
  '/incidents': typeof IncidentsRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/purchase-returns': typeof PurchaseReturnsRoute
  '/purchases': typeof PurchasesRoute
  '/sale-returns': typeof SaleReturnsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock-movements': typeof StockMovementsRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/users': typeof UsersRoute
  '/z-report': typeof ZReportRoute
  '/reports/account-balances': typeof ReportsAccountBalancesRoute
  '/reports/balance-sheet': typeof ReportsBalanceSheetRoute
  '/reports/cashbook': typeof ReportsCashbookRoute
  '/reports/expenses': typeof ReportsExpensesRoute
  '/reports/expiry': typeof ReportsExpiryRoute
  '/reports/inventory-valuation': typeof ReportsInventoryValuationRoute
  '/reports/low-stock': typeof ReportsLowStockRoute
  '/reports/payables': typeof ReportsPayablesRoute
  '/reports/profit-loss': typeof ReportsProfitLossRoute
  '/reports/purchases': typeof ReportsPurchasesRoute
  '/reports/receivables': typeof ReportsReceivablesRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/customers/': typeof CustomersIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/customers/$id/ledger': typeof CustomersIdLedgerRoute
  '/print/purchase/$id': typeof PrintPurchaseIdRoute
  '/print/receipt/$id': typeof PrintReceiptIdRoute
  '/suppliers/$id/ledger': typeof SuppliersIdLedgerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/assistant'
    | '/audit'
    | '/auth'
    | '/barcodes'
    | '/categories'
    | '/customers'
    | '/errors'
    | '/expenses'
    | '/incidents'
    | '/pos'
    | '/products'
    | '/purchase-returns'
    | '/purchases'
    | '/sale-returns'
    | '/sales'
    | '/settings'
    | '/stock-movements'
    | '/suppliers'
    | '/users'
    | '/z-report'
    | '/reports/account-balances'
    | '/reports/balance-sheet'
    | '/reports/cashbook'
    | '/reports/expenses'
    | '/reports/expiry'
    | '/reports/inventory-valuation'
    | '/reports/low-stock'
    | '/reports/payables'
    | '/reports/profit-loss'
    | '/reports/purchases'
    | '/reports/receivables'
    | '/reports/sales'
    | '/customers/'
    | '/reports/'
    | '/suppliers/'
    | '/customers/$id/ledger'
    | '/print/purchase/$id'
    | '/print/receipt/$id'
    | '/suppliers/$id/ledger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/assistant'
    | '/audit'
    | '/auth'
    | '/barcodes'
    | '/categories'
    | '/errors'
    | '/expenses'
    | '/incidents'
    | '/pos'
    | '/products'
    | '/purchase-returns'
    | '/purchases'
    | '/sale-returns'
    | '/sales'
    | '/settings'
    | '/stock-movements'
    | '/users'
    | '/z-report'
    | '/reports/account-balances'
    | '/reports/balance-sheet'
    | '/reports/cashbook'
    | '/reports/expenses'
    | '/reports/expiry'
    | '/reports/inventory-valuation'
    | '/reports/low-stock'
    | '/reports/payables'
    | '/reports/profit-loss'
    | '/reports/purchases'
    | '/reports/receivables'
    | '/reports/sales'
    | '/customers'
    | '/reports'
    | '/suppliers'
    | '/customers/$id/ledger'
    | '/print/purchase/$id'
    | '/print/receipt/$id'
    | '/suppliers/$id/ledger'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/assistant'
    | '/audit'
    | '/auth'
    | '/barcodes'
    | '/categories'
    | '/customers'
    | '/errors'
    | '/expenses'
    | '/incidents'
    | '/pos'
    | '/products'
    | '/purchase-returns'
    | '/purchases'
    | '/sale-returns'
    | '/sales'
    | '/settings'
    | '/stock-movements'
    | '/suppliers'
    | '/users'
    | '/z-report'
    | '/reports/account-balances'
    | '/reports/balance-sheet'
    | '/reports/cashbook'
    | '/reports/expenses'
    | '/reports/expiry'
    | '/reports/inventory-valuation'
    | '/reports/low-stock'
    | '/reports/payables'
    | '/reports/profit-loss'
    | '/reports/purchases'
    | '/reports/receivables'
    | '/reports/sales'
    | '/customers/'
    | '/reports/'
    | '/suppliers/'
    | '/customers/$id/ledger'
    | '/print/purchase/$id'
    | '/print/receipt/$id'
    | '/suppliers/$id/ledger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AssistantRoute: typeof AssistantRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  BarcodesRoute: typeof BarcodesRoute
  CategoriesRoute: typeof CategoriesRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  ErrorsRoute: typeof ErrorsRoute
  ExpensesRoute: typeof ExpensesRoute
  IncidentsRoute: typeof IncidentsRoute
  PosRoute: typeof PosRoute
  ProductsRoute: typeof ProductsRoute
  PurchaseReturnsRoute: typeof PurchaseReturnsRoute
  PurchasesRoute: typeof PurchasesRoute
  SaleReturnsRoute: typeof SaleReturnsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  StockMovementsRoute: typeof StockMovementsRoute
  SuppliersRoute: typeof SuppliersRouteWithChildren
  UsersRoute: typeof UsersRoute
  ZReportRoute: typeof ZReportRoute
  ReportsAccountBalancesRoute: typeof ReportsAccountBalancesRoute
  ReportsBalanceSheetRoute: typeof ReportsBalanceSheetRoute
  ReportsCashbookRoute: typeof ReportsCashbookRoute
  ReportsExpensesRoute: typeof ReportsExpensesRoute
  ReportsExpiryRoute: typeof ReportsExpiryRoute
  ReportsInventoryValuationRoute: typeof ReportsInventoryValuationRoute
  ReportsLowStockRoute: typeof ReportsLowStockRoute
  ReportsPayablesRoute: typeof ReportsPayablesRoute
  ReportsProfitLossRoute: typeof ReportsProfitLossRoute
  ReportsPurchasesRoute: typeof ReportsPurchasesRoute
  ReportsReceivablesRoute: typeof ReportsReceivablesRoute
  ReportsSalesRoute: typeof ReportsSalesRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  PrintPurchaseIdRoute: typeof PrintPurchaseIdRoute
  PrintReceiptIdRoute: typeof PrintReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barcodes': {
      id: '/barcodes'
      path: '/barcodes'
      fullPath: '/barcodes'
      preLoaderRoute: typeof BarcodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-returns': {
      id: '/purchase-returns'
      path: '/purchase-returns'
      fullPath: '/purchase-returns'
      preLoaderRoute: typeof PurchaseReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale-returns': {
      id: '/sale-returns'
      path: '/sale-returns'
      fullPath: '/sale-returns'
      preLoaderRoute: typeof SaleReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-movements': {
      id: '/stock-movements'
      path: '/stock-movements'
      fullPath: '/stock-movements'
      preLoaderRoute: typeof StockMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/z-report': {
      id: '/z-report'
      path: '/z-report'
      fullPath: '/z-report'
      preLoaderRoute: typeof ZReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/account-balances': {
      id: '/reports/account-balances'
      path: '/reports/account-balances'
      fullPath: '/reports/account-balances'
      preLoaderRoute: typeof ReportsAccountBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/balance-sheet': {
      id: '/reports/balance-sheet'
      path: '/reports/balance-sheet'
      fullPath: '/reports/balance-sheet'
      preLoaderRoute: typeof ReportsBalanceSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/cashbook': {
      id: '/reports/cashbook'
      path: '/reports/cashbook'
      fullPath: '/reports/cashbook'
      preLoaderRoute: typeof ReportsCashbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/expenses': {
      id: '/reports/expenses'
      path: '/reports/expenses'
      fullPath: '/reports/expenses'
      preLoaderRoute: typeof ReportsExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/expiry': {
      id: '/reports/expiry'
      path: '/reports/expiry'
      fullPath: '/reports/expiry'
      preLoaderRoute: typeof ReportsExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/inventory-valuation': {
      id: '/reports/inventory-valuation'
      path: '/reports/inventory-valuation'
      fullPath: '/reports/inventory-valuation'
      preLoaderRoute: typeof ReportsInventoryValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/low-stock': {
      id: '/reports/low-stock'
      path: '/reports/low-stock'
      fullPath: '/reports/low-stock'
      preLoaderRoute: typeof ReportsLowStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/payables': {
      id: '/reports/payables'
      path: '/reports/payables'
      fullPath: '/reports/payables'
      preLoaderRoute: typeof ReportsPayablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/profit-loss': {
      id: '/reports/profit-loss'
      path: '/reports/profit-loss'
      fullPath: '/reports/profit-loss'
      preLoaderRoute: typeof ReportsProfitLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/purchases': {
      id: '/reports/purchases'
      path: '/reports/purchases'
      fullPath: '/reports/purchases'
      preLoaderRoute: typeof ReportsPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/receivables': {
      id: '/reports/receivables'
      path: '/reports/receivables'
      fullPath: '/reports/receivables'
      preLoaderRoute: typeof ReportsReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sales': {
      id: '/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof ReportsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/customers/$id/ledger': {
      id: '/customers/$id/ledger'
      path: '/$id/ledger'
      fullPath: '/customers/$id/ledger'
      preLoaderRoute: typeof CustomersIdLedgerRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/print/purchase/$id': {
      id: '/print/purchase/$id'
      path: '/print/purchase/$id'
      fullPath: '/print/purchase/$id'
      preLoaderRoute: typeof PrintPurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/receipt/$id': {
      id: '/print/receipt/$id'
      path: '/print/receipt/$id'
      fullPath: '/print/receipt/$id'
      preLoaderRoute: typeof PrintReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id/ledger': {
      id: '/suppliers/$id/ledger'
      path: '/$id/ledger'
      fullPath: '/suppliers/$id/ledger'
      preLoaderRoute: typeof SuppliersIdLedgerRouteImport
      parentRoute: typeof SuppliersRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersIndexRoute: typeof CustomersIndexRoute
  CustomersIdLedgerRoute: typeof CustomersIdLedgerRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIndexRoute: CustomersIndexRoute,
  CustomersIdLedgerRoute: CustomersIdLedgerRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface SuppliersRouteChildren {
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  SuppliersIdLedgerRoute: typeof SuppliersIdLedgerRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersIndexRoute: SuppliersIndexRoute,
  SuppliersIdLedgerRoute: SuppliersIdLedgerRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AssistantRoute: AssistantRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  BarcodesRoute: BarcodesRoute,
  CategoriesRoute: CategoriesRoute,
  CustomersRoute: CustomersRouteWithChildren,
  ErrorsRoute: ErrorsRoute,
  ExpensesRoute: ExpensesRoute,
  IncidentsRoute: IncidentsRoute,
  PosRoute: PosRoute,
  ProductsRoute: ProductsRoute,
  PurchaseReturnsRoute: PurchaseReturnsRoute,
  PurchasesRoute: PurchasesRoute,
  SaleReturnsRoute: SaleReturnsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  StockMovementsRoute: StockMovementsRoute,
  SuppliersRoute: SuppliersRouteWithChildren,
  UsersRoute: UsersRoute,
  ZReportRoute: ZReportRoute,
  ReportsAccountBalancesRoute: ReportsAccountBalancesRoute,
  ReportsBalanceSheetRoute: ReportsBalanceSheetRoute,
  ReportsCashbookRoute: ReportsCashbookRoute,
  ReportsExpensesRoute: ReportsExpensesRoute,
  ReportsExpiryRoute: ReportsExpiryRoute,
  ReportsInventoryValuationRoute: ReportsInventoryValuationRoute,
  ReportsLowStockRoute: ReportsLowStockRoute,
  ReportsPayablesRoute: ReportsPayablesRoute,
  ReportsProfitLossRoute: ReportsProfitLossRoute,
  ReportsPurchasesRoute: ReportsPurchasesRoute,
  ReportsReceivablesRoute: ReportsReceivablesRoute,
  ReportsSalesRoute: ReportsSalesRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  PrintPurchaseIdRoute: PrintPurchaseIdRoute,
  PrintReceiptIdRoute: PrintReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
